# -*- coding: utf-8 -*-
lines = []
lines.append("[gd_scene load_steps=3 format=3 uid=\"uid://doxq6iubcxvq0\"]")
lines.append("")
lines.append("[ext_resource type=\"Script\" path=\"res://scripts/game_manager.gd\" id=\"1\"]")
lines.append("[ext_resource type=\"Script\" path=\"res://scripts/micro_board.gd\" id=\"2\"]")
lines.append("[ext_resource type=\"Script\" path=\"res://scripts/cell.gd\" id=\"3\"]")
lines.append("")
lines.append("[node name=\"Game\" type=\"Control\"]")
lines.append("anchors_preset = 15")
lines.append("anchor_right = 1.0")
lines.append("anchor_bottom = 1.0")
lines.append("grow_horizontal = 2")
lines.append("grow_vertical = 2")
lines.append("")
lines.append("[node name=\"GameManager\" type=\"Node\" parent=\".\"]")
lines.append("script = ExtResource(\"1\")")
lines.append("")
lines.append("[node name=\"Board\" type=\"Node2D\" parent=\".\"]")
lines.append("")
lines.append("[node name=\"MacroGrid\" type=\"GridContainer\" parent=\"Board\"]")
lines.append("columns = 3")
lines.append("theme_override_constants/h_separation = 8")
lines.append("theme_override_constants/v_separation = 8")
lines.append("layout_mode = 0")
lines.append("position = Vector2(250, 150)")
lines.append("size = Vector2(600, 600)")

for mr in range(3):
    for mc in range(3):
        mn = "MicroBoard_" + str(mr) + "_" + str(mc)
        mp = "Board/MacroGrid/" + mn
        lines.append("")
        lines.append("[node name=\"" + mn + "\" type=\"Control\" parent=\"Board/MacroGrid\"]")
        lines.append("script = ExtResource(\"2\")")
        lines.append("macro_pos = Vector2i(" + str(mc) + ", " + str(mr) + ")")
        lines.append("layout_mode = 2")
        lines.append("custom_minimum_size = Vector2(180, 180)")
        lines.append("size_flags_horizontal = 3")
        lines.append("size_flags_vertical = 3")
        lines.append("")
        lines.append("[node name=\"CellGrid\" type=\"GridContainer\" parent=\"" + mp + "\"]")
        lines.append("layout_mode = 1")
        lines.append("anchors_preset = 15")
        lines.append("anchor_right = 1.0")
        lines.append("anchor_bottom = 1.0")
        lines.append("grow_horizontal = 2")
        lines.append("grow_vertical = 2")
        lines.append("columns = 3")
        lines.append("theme_override_constants/h_separation = 2")
        lines.append("theme_override_constants/v_separation = 2")
        for cr in range(3):
            for cc in range(3):
                cn = "Cell_" + str(cr) + "_" + str(cc)
                lines.append("")
                lines.append("[node name=\"" + cn + "\" type=\"Button\" parent=\"" + mp + "/CellGrid\"]")
                lines.append("layout_mode = 2")
                lines.append("size_flags_horizontal = 3")
                lines.append("size_flags_vertical = 3")
                lines.append("disabled = true")
                lines.append("text = \"\"")

lines.append("")
lines.append("[node name=\"MacroWinLine\" type=\"Line2D\" parent=\"Board\"]")
lines.append("visible = false")
lines.append("default_color = Color(0, 0, 0, 0)")
lines.append("width = 6.0")
lines.append("")
lines.append("[node name=\"UI\" type=\"CanvasLayer\" parent=\".\"]")
lines.append("")
lines.append("[node name=\"StatusLabel\" type=\"Label\" parent=\"UI\"]")
lines.append("layout_mode = 0")
lines.append("position = Vector2(400, 30)")
lines.append("size = Vector2(400, 40)")
lines.append("theme_override_font_sizes/font_size = 28")
lines.append("horizontal_alignment = 1")
lines.append("text = \"\u8d85\u7ea7\u4e95\u5b57\u68cb - X \u5148\u624b\"")
lines.append("")
lines.append("[node name=\"FreeChoiceHint\" type=\"Label\" parent=\"UI\"]")
lines.append("layout_mode = 0")
lines.append("position = Vector2(300, 80)")
lines.append("size = Vector2(600, 30)")
lines.append("theme_override_font_sizes/font_size = 16")
lines.append("horizontal_alignment = 1")
lines.append("visible = false")
lines.append("text = \"\"")
lines.append("")
lines.append("[node name=\"UndoButton\" type=\"Button\" parent=\"UI\"]")
lines.append("layout_mode = 0")
lines.append("position = Vector2(440, 770)")
lines.append("size = Vector2(120, 40)")
lines.append("text = \"\u6094\u68cb\"")
lines.append("disabled = true")
lines.append("")
lines.append("[node name=\"ResetButton\" type=\"Button\" parent=\"UI\"]")
lines.append("layout_mode = 0")
lines.append("position = Vector2(300, 770)")
lines.append("size = Vector2(120, 40)")
lines.append("text = \"\u91cd\u65b0\u5f00\u59cb\"")

with open("E:/Create/Projects/ultimate-tic-tac-toe/scenes/game.tscn", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("DONE")
